/* 應用層｜跨模組共用、且會被重新指定的狀態（目前的宇宙、攝影機縮放、播放時間、畫質等）。
   其他模組一律透過 S.xxx 讀寫，確保大家看到的是同一份值。 */
export const S = {
  U: null,
  // 宇宙參數的唯讀鏡像（方便繪製時使用；真正的值在 S.U.p，重新開始時同步）
  HUB: .25,
  RH: 140,
  R0: 3,
  RGEN: 3000,
  PRESIM: 18,
  HIST: 1200,
  PAL: [],
  qLevel: 1,
  qMode: '1',
  fpsCap: 60,
  tView: 0,
  isLive: true,
  playing: true,
  simPaused: false,   // 暫停演化（模擬本身停止；與只暫停畫面的「播放／暫停」不同）
  speed: 1,
  scrubbing: false,
  selected: null,
  pendingCol: [],
  vw: 0,
  vh: 0,
  dpr: 1,
  Z: 1,
  minZ: .3,
  zoomAnim: null,
  vis: [],
  maxPathCoord: 0,
  texLastT: null,
  texSpeedSeen: 0,
  obsEndKey: '',
  prevT: 0,
  workEma: 5,
  fpsEma: 60,
  frames: 0,
  fpsShown: 0,
  fpsClock: 0,
  last: performance.now(),
};
